### PR TITLE
Use Conda Packages

### PR DESCRIPTION
**Pull request by jan-janssen**
Superseed https://github.com/muh-hassani/pyiron-precice-image/pull/1

### CODE REVIEW

**Comment by max-hassani** [comment]
I guess the [line](https://github.com/jan-janssen/pyiron-precice-image/blob/25f30ab2b04e20d705dde06c5021eaf2e2a7ad47/.github/workflows/testing.yml#L12) is extra and causes the testing workflow not to run. I tried to modify it on your fork, but was not possible.

**Comment by max-hassani** [comment]
The test hangs as it awaits a given time zone from the command line. As I read [here](https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image), the following lines in the dockerfile should solve the issue.
```
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin
```

**Comment by jan-janssen** [comment]
Ok, maybe it is easier if you fix it.

**Comment by max-hassani** [comment]
Ok, so I will create a seperate PR. Thanks a lot for creating the conda packages and suggested changes.

**Pull request closed without merging**
